version: '3.8'
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - "8000:8000"   # Splunk Web
      - "8088:8088"   # HTTP Event Collector
      - "8089:8089"   # Management Port
    restart: unless-stopped`  
